namespace Hikan.Core
{
    /// <summary>英語パラメータ名 → 日本語説明の対応(内部保持)。schema_version は含めない。</summary>
    public static class HikanNames
    {
        public static readonly System.Collections.Generic.Dictionary<string, string> Japanese =
            new System.Collections.Generic.Dictionary<string, string>
            {
                { "inner_width", "内空幅 B" },
                { "inner_height", "内空高 H" },
                { "wall_thickness", "側壁厚" },
                { "top_slab_thickness", "頂版厚" },
                { "bottom_slab_thickness", "底版厚" },
                { "barrel_length", "函体延長 L(斜距離)" },
                { "bottom_slope", "底版勾配 i(下流下がり)" },
                { "soil_cover", "土かぶり" },
                { "block_count", "ブロック数" },
                { "excavation_margin", "床掘り余裕幅(片側)" },
                { "excavation_slope", "床掘り法勾配 1:n の n" },
                { "foundation_thickness", "基礎材厚(均しコン等)" },
                { "upstream_breast_stem_thickness", "川裏側胸壁 たて壁厚(0 で設置しない)" },
                { "upstream_breast_position", "川裏側胸壁 たて壁軸位置(川裏函体端から)" },
                { "upstream_breast_length", "川裏側胸壁 張出し長(函体側面から外向き、左右同一)" },
                { "upstream_breast_crown_height", "川裏側胸壁 天端高(函体底版下面から)" },
                { "upstream_breast_embedment", "川裏側胸壁 根入れ深さ" },
                { "upstream_breast_footing_thickness", "川裏側胸壁 底版厚" },
                { "upstream_breast_toe_length", "川裏側胸壁 つま先版長(川裏側)" },
                { "upstream_breast_heel_length", "川裏側胸壁 かかと版長(函体中央側)" },
                { "downstream_breast_stem_thickness", "川表側胸壁 たて壁厚(0 で設置しない)" },
                { "downstream_breast_position", "川表側胸壁 たて壁軸位置(川裏函体端から)" },
                { "downstream_breast_length", "川表側胸壁 張出し長(函体側面から外向き、左右同一)" },
                { "downstream_breast_crown_height", "川表側胸壁 天端高(函体底版下面から)" },
                { "downstream_breast_embedment", "川表側胸壁 根入れ深さ" },
                { "downstream_breast_footing_thickness", "川表側胸壁 底版厚" },
                { "downstream_breast_toe_length", "川表側胸壁 つま先版長(川表側)" },
                { "downstream_breast_heel_length", "川表側胸壁 かかと版長(函体中央側)" },
                { "cutoff_count", "しゃ水壁 枚数(0 で設置しない)" },
                { "cutoff_thickness", "しゃ水壁 厚" },
                { "cutoff_projection", "しゃ水壁 張出し量(全周一律)" },
                { "color_index", "ソリッド色(ACI)" },
                { "base_x", "基準点 X(函体中心線)" },
                { "base_y", "基準点 Y(上流端)" },
                { "base_z", "基準点 Z(底版下面)" },

                { "outer_width", "外形幅 B_out" },
                { "outer_height", "外形高 H_out" },
                { "invert_level", "敷高(内空底面高)" },
                { "outer_section_area", "外形断面積" },
                { "inner_section_area", "内空断面積" },
                { "concrete_section_area", "コンクリート断面積" },
                { "top_slab_volume", "頂版コンクリート" },
                { "bottom_slab_volume", "底版コンクリート" },
                { "wall_volume", "側壁コンクリート" },
                { "barrel_concrete_volume", "函体コンクリート計" },
                { "upstream_breast_volume", "川裏側胸壁コンクリート(左右計)" },
                { "downstream_breast_volume", "川表側胸壁コンクリート(左右計)" },
                { "cutoff_total_volume", "しゃ水壁コンクリート計" },
                { "cutoff_spacing", "しゃ水壁 設置間隔" },
                { "seepage_path_length", "浸透路長(函体外周)" },
                { "concrete_volume", "コンクリート総計(函体+胸壁+しゃ水壁)" },
                { "horizontal_projection", "水平投影長" },
                { "drop_height", "上下流端の落差" },
                { "formwork_inner", "型枠(内空面)" },
                { "formwork_outer_side", "型枠(外側面)" },
                { "formwork_top", "型枠(頂版上面)" },
                { "formwork_end", "型枠(端面)" },
                { "formwork_breast", "型枠(胸壁)" },
                { "formwork_cutoff", "型枠(しゃ水壁)" },
                { "block_length", "ブロック長" },
                { "concrete_per_block", "ブロック当りコンクリート" },
                { "excavation_bottom_width", "床掘り底面幅" },
                { "excavation_bottom_length", "床掘り底面長" },
                { "excavation_depth", "床掘り深さ" },
                { "excavation_volume", "床掘り体積" },
                { "foundation_volume", "基礎材体積" },
                { "occupied_volume", "構造物地下占有体積" },
                { "backfill_volume", "埋戻体積" },
                { "surplus_volume", "残土(地山換算)" }
            };
    }
}
